server:
  port: 8891

eureka:
  client:
    service-url:
      defaultZone: http://172.16.62.68:8880/eureka/

spring:
  application:
    name: web-mgr

  redis:
    database: 0
    host: 192.168.31.128
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000