server:
  port: 8891

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://172.16.62.68:8880/eureka/

spring:
  application:
    name: web-mgr

  redis:
    database: 0
    host: 192.168.31.129
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
    timeout: 5000

  main:
    allow-bean-definition-overriding: true