#开发环境
server:
  #端口号
  port: 8082
  #项目名，如果不设定，默认是 /
  context-path: /

spring:
  datasource:
    username: root
    password: admin123A@2018
    url: jdbc:mysql://192.168.230.128:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.service.service.model
  configuration:
    map-underscore-to-camel-case: true