#开发环境
server:
  #端口号
  port: 8083

  application:
    name: eureka-client

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
        defaultZone: http://localhost:8083/eureka/