#开发环境
server:
  #端口号
  port: 8083

  application:
    name: eureka-client

eureka:
  environment: eureka-client
  instance:
    preferIpAddress: true #客户端在注册时就会使用自己的ip地址而不是主机名(客户端自身加)
    leaseRenewalIntervalInSeconds: 10 # 心跳时间，即服务续约间隔时间（缺省为30s）
    instanceId: ${spring.cloud.client.ipAddress}:${server.port} #注册的时候显示ip: 端口
    leaseExpirationDurationInSeconds: 10 # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    registerWithEureka: true #是否注册自己
    fetchRegistry: true #是否需要去检索寻找服务，默认是true
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）
    serviceUrl:
        defaultZone: http://localhost:8083/eureka/ #注册中心地址