server:
  port: 8880
spring:
  application:
    name: eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://172.16.62.68:8880/eureka/

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'